sudo: false
language: go
go:
  - 1.6.4
services:
  - mysql
before_install:
  - make testsetup
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
before_install:
  - test -d $GOPATH/bin || mkdir -p $GOPATH/bin
install:
  ## Install dependencies
  - glide install
script:
  - go test
